security:
    # Hash passwords for your User entity
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Load users from database
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: login      # route for login page
                check_path: login      # route that processes login
                default_target_path: / # redirect after login
            logout:
                path: logout
                target: /
            custom_authenticator: App\Security\EmailAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
            cost: 4
            time_cost: 3
            memory_cost: 10
